// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrulaemtxghsismojwln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFydWxhZW10eGdoc2lzbW9qd2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODM1NTYsImV4cCI6MjA2NTA1OTU1Nn0.nkRPhrK8sw0S3Qj1k8SLNeXCC1L4zUn5TylmOsKocnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);